### PR TITLE
Add diagrams section

### PR DESCRIPTION
**Pull request by scottongithub**
Hi all! 

I saw someone asking in Slack a few weeks back if there was an overview of what's going on technically with Omni/LiteBeam nodes. I figured I'd make a diagram of it and put it into a new (top-level) Diagrams section. 

I've also made a new 'assets' directory in the root, with a 'diagrams_source' directory in it so diagrams can be loaded up and edited using app.diagrams.net (formerly draw.io). Not sure if this is where we would prefer the source to go.

Thoughts and suggestions are much appreciated - glad to change anything around and to create any other diagrams that are requested.

thanks

### CODE REVIEW

**Comment by scottongithub** [comment]
Will clean up commits so there's only one: "Add Diagrams section"

**Comment by scottongithub** [comment]
resubmitting

**Comment by danielhmetro** [comment]
Very cool diagram. Not sure if feasible but would it make sense to have them be SVGs or some other format editable in case if changes? (or if there is a way to paste a link to the diagram file itself)

Also, is there a need to have a whole subheading for diagrams, or could we just upload the diagrams to a folder and embed them?

**Comment by scottongithub** [comment]
PR was cleaned up and resubmitted as #170. Going to move this conversation over there

**Pull request closed without merging**
