### PR TITLE
WIP: Documentation content reorganization and "guidebook" improvements

### PR DESCRIPTION
**Pull request by meitar**
This pull request will coalesce my work on reorganizing major portions of the NYC Mesh Docs website into a more "guidebook"-like structure. The goals for this work are to:

* Lessen the steep learning curve for newcomers who may not have as much technical experience with computer internetworking concepts as veteran NYC mesh members.
* Re-order existing content along a well-defined learning path that prioritizes immediate, material expansion of the mesh "from the leaves towards the root" (end-user devices first).
* Add new content for specifically beginner and intermediate level networking concepts as they relate to the existing implementation of the NYC Mesh network.
* Provide links to off-site reference material that can supplement a newcomer's understanding while reducing our overall workload and maintenance commitment.
* Improve the published quality of the documentation by fixing numerous formatting issues and making better use of the HTML vocabulary.

The branch on which this pull request is based will only contain minor modifications to the page content of the site; no major templating changes will be committed here.

### CODE REVIEW

**Comment by woa100** [comment]
hey meitar, do you have a slack handle?

**Comment by woa100** [comment]
Thanks for doing this, the intro page looks a lot better.
I recommend you reach out to Scott Rasmussen on slack about standard Mesh copy he has been working to coordinate for the "about Mesh" section. This will help us line up all of our copy across media and platforms.

**Comment by woa100** [comment]
I would also recommend reaching out on slack about larger-scale reorganization issues to prepare people for changes.

**Comment by woa100** [comment]
Keep it up!

**Comment by meitar** [comment]
@woa100 I do have a Slack handle but I rarely use it because I find Slack unbearably painful to use. Thanks for the pointers, regardless. :)

**Comment by woa100** [comment]
@meitar i know slack can be overwhelming for me too - not everyone who is on slack is on github however so if you want to maximize your input and feedback on website / docs changes I suggest reaching out there as well

**Comment by woa100** [comment]
Even if it's just to announce changes to the broader community

**Comment by woa100** [comment]
And then you close it and don't open it again for a week!

**Pull request merged**
