### PR TITLE
First pass at major reorgnization.

### PR DESCRIPTION
**Pull request by meitar**
This is a big commit. I have radically reorganized the structure of the
Docs website in order to continue the work that began in #97. I have
changed the names and filepaths of numerous documentation sections so
that they are ready to receive "guidebook"-style improvements. Notably,
this includes the "Networking" and "Organization" sections, whose names
I found ambiguous and whose contents could be better distinguished, IMO.

The new names of the documentation sections should (I hope) make clear
the direction in which I am working: I want it to be possible for a
complete NYC Mesh "newbie" to look at the outline of the documentation
generated by Hugo and have a clear idea of where they should start
reading to accomplish a given task.

This is aided by a complete rewrite of the "Getting Started" page, which
now offers additional guidance about which part of the documentation to
read based on the role or goal that the reader wants to accomplish.

Additionally, I have expanded the outline by adding numerous new
sections, including an expanded "Continuing Education" section (which
now houses the links to NYC Mesh's "Networking Classes" along with links
to other free and by-donation in-person computer networking workshops
organized by NYC Mesh volunteers and contributors), a new
as-yet-unwritten "Troublehsooting Guide," and an important layperson's
"Overview" section that describes technical details about the NYC Mesh
implementation.

Using Hugo's `aliases` feature, I have also supplied numerous redirects
to various important parts of the old documentation for which the URL
permalinks have changed, so that these links do not break. However, this
URL redirection coverage may not be complete as I am not intimately
familiar with all the places that incoming links may be published.

This is a work-in-progress, but I believe is complete enough for the
direction of my work to be clear.

### CODE REVIEW

**Comment by bhny** [comment]
What is the reason for the last revert?

**Comment by meitar** [comment]
> What is the reason for the last revert?

There is no revert affecting this pull request.

**Comment by bhny** [comment]
There's a fork where it is reverted so I guess that means something. I appreciate all the work you are doing but I'm not following this revert.

**Comment by meitar** [comment]
> There's a fork where it is reverted

That's my fork of the documentation where I am continuing to document NYC Mesh independently.

> so I guess that means something.

It means I am documenting NYC Mesh independently.

> I appreciate all the work you are doing

Thanks. I appreciate the work you are doing, too. :)

> but I'm not following this revert.

The commit message on the revert's commit explains my reasoning behind it.

**Comment by bhny** [comment]
OK, you are welcome to fork obviously! Hopefully we'll merge in the future. There were debates about the "community-owned network" thing years ago, and we reached consensus that we are not an ISP. Wording is a big part of our identity of course so we're not going to budge on this one.

**Comment by meitar** [comment]
> Hopefully we'll merge in the future.

You are more than welcome to pull any of my work from my fork, and edit it to your liking. :)

> There were debates about the "community-owned network" thing years ago, and we reached consensus that we are not an ISP. Wording is a big part of our identity of course so we're not going to budge on this one.

I totally understand! I don't expect or even really desire that you change your position on this. That's why I forked and invite you to pull whatever changes you like (and only the changes you like) back to your fork at your own convenience.

Good luck with all that you're working on and I look forward to seeing what comes of your efforts in the future. :)

**Comment by meitar** [comment]
As there appears to be no interest from NYC Mesh in merging this greatly expanded and far improved version of the existing documentation, rather than continuing to look at an open PR on my GitHub dashboard, I am closing this myself.

For anyone who stumbles upon this, please note that there is [improved NYC Mesh documentation available at https://nycmesh-docs.netlify.com](https://nycmesh-docs.netlify.com/).

**Pull request closed without merging**
